spring:
    datasource:
        url: jdbc:mysql://192.168.10.188:3306/ckdx-1?allowMultiQueries=true&useUnicode=true&serverTimezone=CTT&characterEncoding=utf-8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        sql-script-encoding: utf-8
        hikari:
          connection-timeout: 120000
          maximum-pool-size: 10
          idleTimeout: 9000
          max-lifetime: 1765000
        #连接池的配置信息
#        initialSize: 10
#        minIdle: 10
#        maxActive: 100
#        maxWait: 60000
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: SELECT 1 FROM DUAL
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxPoolPreparedStatementPerConnectionSize: 20
logging:
#  level: 
#    root: warn
  file: logs/dhys.log
  