spring:
    datasource:
        url: jdbc:mysql://192.168.10.188:3306/dev?allowMultiQueries=true&useUnicode=true&serverTimezone=CTT&characterEncoding=utf-8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: ckdx
        password: ENC(4jCAFhZVpK0AQK61GLkwOA==)
        sql-script-encoding: utf-8
        hikari:
          connection-timeout: 120000
          maximum-pool-size: 10
          idleTimeout: 9000
          max-lifetime: 1765000

logging:
#  level: 
#    root: warn
  file: logs/dhys.log