spring:
    datasource:
        url: jdbc:mysql://192.168.10.181:3306/ckdx?allowMultiQueries=true&useUnicode=true&serverTimezone=CTT&characterEncoding=utf-8&useUnicode=true&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: ckdx
        password: ENC(WxqNqsZ2+VnI2H73WtxGDmPLbeMpPzkz)
        sql-script-encoding: utf-8
        hikari:
          connection-timeout: 120000
          maximum-pool-size: 50
          idleTimeout: 9000
          max-lifetime: 1765000
logging:
  level: 
    root: warn
  file: logs/dhys.log
    